#!/usr/bin/env python

import sys

if __name__ == '__main__':

    margin = 1.2

    price_old = float(sys.argv[1])
    price_new = margin*price_old
    asset_old = float(sys.argv[2])
    unit_buy = asset_old/price_old
    unit_sell = (1-((1-(1/margin))/3))*unit_buy
    unit_keep = unit_buy-unit_sell
    asset_new = unit_sell*price_new
    asset_keep = (asset_new-asset_old)/2

    print(f'Margin: {round(margin, 2)}')
    print(f'Buy {round(unit_buy, 2)} units at {round(price_old, 5)}, pay {round(asset_old, 2)}.')
    print(f'Sell {round(unit_sell, 2)} units at {round(price_new, 5)}, get {round(asset_new, 2)} and keep {round(unit_keep, 2)} units.')
    print(f'Reinvest {round(asset_new-asset_keep, 2)}, keep {round(asset_keep, 2)}.')
